apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        key: value
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
